(()=>{
const CATCH_BUILD='catchment-2',PURPLE='#b58cff',STEPS=[10,20,30,40,45,50,60,70,80];let configured=45,manualView=false;
const style=document.createElement('style');style.textContent=`.status{pointer-events:auto;cursor:pointer}.status .viewstate{color:${PURPLE}}.catchpick{position:fixed;right:16px;top:72px;z-index:20;background:#020a10;border:1px solid #24485c;padding:8px;display:none;box-shadow:0 8px 30px #000}.catchpick.show{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.catchpick button{background:#06131c;border:1px solid #24485c;color:#8aa9b8;font:10px ui-monospace;padding:7px 9px}.catchpick button.on{color:#62ddff;border-color:#62ddff}`;document.head.appendChild(style);
const picker=document.createElement('div');picker.className='catchpick';document.body.appendChild(picker);
function centered(){return hav(YOW.lat,YOW.lon,view.cy,view.cx)<Math.max(1,configured*.025)}
function extent(){const a=area(),c=unproject(a.cx,a.cy),edge=unproject(a.left+a.w,a.cy);return Math.max(1,Math.round(hav(c.lat,c.lon,edge.lat,edge.lon)))}
function inView(a){const q=project(a.lat,a.lon),z=area();return q.x>=z.left&&q.x<=z.left+z.w&&q.y>=z.top&&q.y<=innerHeight-z.bottom}
function visible(){return aircraft.filter(a=>!a.ground&&inView(a))}
function mode(){let e=extent(),same=centered()&&Math.abs(e-configured)<=Math.max(2,configured*.06);return{e,center:centered(),live:same&&!manualView}}
function paintStatus(j){let m=mode(),list=visible(),label=m.center?'YOW':'VIEW',radius=m.live?configured:m.e,cls=m.live?'live':'viewstate';status.innerHTML=`<span class="${cls}">${list.length} AIRBORNE / ${label} ${radius}</span><br>${j.provider||'ADS-B'} · <b>${new Date(j.now||Date.now()).toISOString().slice(11,19)}Z</b>`}
function renderPicker(){picker.innerHTML=STEPS.map(n=>`<button data-r="${n}" class="${n===configured?'on':''}">${n} NM</button>`).join('');picker.querySelectorAll('button').forEach(b=>b.onclick=e=>{e.stopPropagation();configured=Number(b.dataset.r);reset();picker.classList.remove('show');renderPicker();refresh()})}
status.addEventListener('click',e=>{e.stopPropagation();picker.classList.toggle('show')});document.addEventListener('click',()=>picker.classList.remove('show'));renderPicker();
const baseManual=manual;manual=function(){manualView=true;baseManual()};
const baseReset=reset;reset=function(){view={cx:YOW.lon,cy:YOW.lat,zoom:45/configured};manualView=false;recenter.classList.remove('show');tileSig='';draw();if(window.drawGeo)window.drawGeo(true)};
const baseDraw=draw;draw=function(){baseDraw();if(lastGood)paintStatus({provider:window.__doaaProvider||'ADS-B',now:window.__doaaNow||Date.now()})};
refresh=async function(){try{let need=Math.min(80,Math.max(configured,extent()+Math.ceil(hav(YOW.lat,YOW.lon,view.cy,view.cx)))),r=await fetch(`/api/traffic?dist=${need}&_=${Date.now()}`,{cache:'no-store'}),j=await r.json();build.textContent=`UI ${UI} · API ${j.build||'LEGACY'} · ${CATCH_BUILD}`;if(!r.ok||!j.ok)throw Error((j.errors||[`HTTP ${r.status}`]).join(' · '));aircraft=(j.aircraft||[]).map(norm).filter(a=>a&&a.id).sort((a,b)=>(a.ground-b.ground)||a.d-b.d);tracks=new Map(Object.entries(j.tracks||{}).map(([id,e])=>[id.toLowerCase(),e]));lastGood=Date.now();window.__doaaProvider=j.provider;window.__doaaNow=j.now;if(selected&&!aircraft.some(a=>a.id===selected))select(null);renderRack();paintStatus(j);draw()}catch(e){status.innerHTML=lastGood?`<span class="warn">HOLDING LAST PICTURE</span><br><b>REACQUIRING…</b>`:`<span class="warn">DATA LINK UNAVAILABLE</span><br><b>RETRYING…</b>`}};
const oldRack=renderRack;renderRack=function(){let all=aircraft,keep=aircraft.filter(a=>a.ground||inView(a));aircraft=keep;oldRack();aircraft=all};
reset();refresh();
})();