(()=>{
const MAP_BUILD='vector-2';
const old=document.getElementById('map');if(old){old.replaceChildren();old.style.cssText='display:none!important'}
const attr=document.querySelector('.attrib');
const geo=document.createElement('canvas');geo.id='geo';geo.style.cssText='position:absolute;inset:0;width:100%;height:100%;pointer-events:none;z-index:0;background:#02070c';
const sky=document.getElementById('sky');sky.parentNode.insertBefore(geo,sky);sky.style.zIndex='1';
const g=geo.getContext('2d');let features=[],ready=false,lastKey='',state='LOADING';
const Q='[out:json][timeout:25];(way[waterway~"river|canal"](44.55,-76.70,46.05,-74.65);way[highway~"motorway|trunk|primary"](44.55,-76.70,46.05,-74.65););out geom;';
function report(){if(attr){attr.textContent=`MAP ${MAP_BUILD} · ${state}${ready?` · ${features.length} FEATURES`:''} · © OPENSTREETMAP CONTRIBUTORS`;attr.style.color='rgba(98,221,255,.72)';attr.style.fontSize='8px';attr.style.zIndex='4'}}
function classify(e){const t=e.tags||{};if(t.waterway){let n=(t.name||'').toLowerCase();return{kind:'water',major:/ottawa|outaouais/.test(n)?3:/rideau/.test(n)?2:1,name:t.name||''}}return{kind:'road',major:t.highway==='motorway'?3:t.highway==='trunk'?2:1,name:t.ref||t.name||''}}
function simplify(a,step){if(a.length<=3)return a;const out=[a[0]];for(let i=step;i<a.length-1;i+=step)out.push(a[i]);out.push(a[a.length-1]);return out}
async function load(){report();try{const u='https://overpass-api.de/api/interpreter?data='+encodeURIComponent(Q),r=await fetch(u);if(!r.ok)throw Error(`HTTP ${r.status}`);const j=await r.json();features=(j.elements||[]).filter(e=>e.geometry?.length>1).map(e=>({pts:simplify(e.geometry,e.geometry.length>120?4:e.geometry.length>50?2:1),...classify(e)}));ready=features.length>0;state=ready?'READY':'EMPTY';report();drawGeo(true)}catch(e){state='FAILED '+String(e.message||e).slice(0,28).toUpperCase();report();console.warn('DOAA vector geography unavailable',e)}}
function path(f){g.beginPath();for(let i=0;i<f.pts.length;i++){let q=project(f.pts[i].lat,f.pts[i].lon);i?g.lineTo(q.x,q.y):g.moveTo(q.x,q.y)}g.stroke()}
function drawGeo(force=false){if(!ready)return;const key=[innerWidth,innerHeight,view.cx.toFixed(4),view.cy.toFixed(4),view.zoom.toFixed(3)].join(':');if(!force&&key===lastKey)return;lastKey=key;const d=devicePixelRatio||1;if(geo.width!==Math.round(innerWidth*d)||geo.height!==Math.round(innerHeight*d)){geo.width=Math.round(innerWidth*d);geo.height=Math.round(innerHeight*d);geo.style.width=innerWidth+'px';geo.style.height=innerHeight+'px'}g.setTransform(d,0,0,d,0,0);g.clearRect(0,0,innerWidth,innerHeight);g.fillStyle='#02070c';g.fillRect(0,0,innerWidth,innerHeight);g.lineCap='round';g.lineJoin='round';
for(const f of features.filter(x=>x.kind==='road')){g.shadowBlur=0;g.strokeStyle=f.major===3?'rgba(78,151,178,.58)':f.major===2?'rgba(63,126,151,.42)':'rgba(51,103,124,.30)';g.lineWidth=(f.major===3?1.35:f.major===2?1:.7)*Math.min(1.7,Math.max(.8,view.zoom));path(f)}
for(const f of features.filter(x=>x.kind==='water')){g.shadowColor='rgba(36,205,245,.42)';g.shadowBlur=f.major===3?7:f.major===2?4:2;g.strokeStyle=f.major===3?'rgba(43,207,245,.98)':f.major===2?'rgba(49,189,226,.86)':'rgba(40,139,170,.52)';g.lineWidth=(f.major===3?11:f.major===2?5.5:1.7)*Math.min(1.8,Math.max(.85,view.zoom));path(f)}g.shadowBlur=0}
addEventListener('resize',()=>drawGeo(true));setInterval(drawGeo,120);load();
})();