const http=require('http');
const PORT=process.env.PORT||10000,CYOW={lat:45.3225,lon:-75.6692};
const SOURCES=[{name:'ADSB.FI',url:d=>`https://opendata.adsb.fi/api/v3/lat/${CYOW.lat}/lon/${CYOW.lon}/dist/${d}`},{name:'ADSB.ONE',url:d=>`https://api.adsb.one/v2/point/${CYOW.lat}/${CYOW.lon}/${d}`},{name:'ADSB.LOL',url:d=>`https://api.adsb.lol/v2/point/${CYOW.lat}/${CYOW.lon}/${d}`}];
const UA='DOAA-Ottawa-Aviation/1.0 (+https://github.com/brenton-collab/doaa-calibration)',TIMEOUT=3500,CACHE_MS=30000,TRACK_KEEP=90*60*1000,ABSENT_CLOSE=15*60*1000;
let cache=null,cacheAt=0,inFlight=null;const encounters=new Map();
const ident=a=>String(a.hex||a.icao||'').toLowerCase();
function observe(list,now){const seen=new Set();for(const a of list){const id=ident(a);if(!id||a.lat==null||a.lon==null||a.alt_baro==='ground')continue;seen.add(id);let e=encounters.get(id);if(!e)e={id,firstSeen:now,lastSeen:now,points:[]};e.lastSeen=now;const last=e.points[e.points.length-1];if(!last||now-last.t>=25000)e.points.push({lat:a.lat,lon:a.lon,t:now,alt:a.alt_baro??a.alt_geom??null,gs:a.gs??null,track:a.track??null});e.points=e.points.filter(p=>now-p.t<TRACK_KEEP);encounters.set(id,e)}for(const[id,e]of encounters)if(now-e.lastSeen>ABSENT_CLOSE)encounters.delete(id)}
function trackPayload(){const out={};for(const[id,e]of encounters)out[id]={firstSeen:e.firstSeen,lastSeen:e.lastSeen,points:e.points};return out}
async function sourceFetch(source,dist){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),TIMEOUT);try{const r=await fetch(source.url(dist),{headers:{Accept:'application/json','User-Agent':UA},signal:controller.signal});if(!r.ok)throw new Error(String(r.status));const j=await r.json(),now=Date.now(),aircraft=j.ac||j.aircraft||[];observe(aircraft,now);return{ok:true,relay:'render-2',provider:source.name,now,aircraft,tracks:trackPayload()}}finally{clearTimeout(timer)}}
async function acquire(dist){const errors=[];for(const source of SOURCES){try{return await sourceFetch(source,dist)}catch(e){errors.push(`${source.name}: ${e.name==='AbortError'?'TIMEOUT':e.message}`)}}return{ok:false,relay:'render-2',now:Date.now(),aircraft:[],tracks:trackPayload(),errors}}
async function traffic(dist){if(cache&&Date.now()-cacheAt<CACHE_MS)return{...cache,tracks:trackPayload(),cached:true};if(!inFlight)inFlight=acquire(dist).then(x=>{if(x.ok){cache=x;cacheAt=Date.now()}return x}).finally(()=>{inFlight=null});return inFlight}
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host}`);res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Access-Control-Allow-Origin','*');if(u.pathname==='/health')return res.end(JSON.stringify({ok:true,service:'DOAA ADS-B Relay',build:'render-2',encounters:encounters.size}));if(u.pathname!=='/traffic'){res.statusCode=404;return res.end(JSON.stringify({ok:false,error:'not found'}))}const dist=Math.max(1,Math.min(80,Number(u.searchParams.get('dist')||45)));try{const data=await traffic(dist);res.statusCode=data.ok?200:502;res.setHeader('Cache-Control',data.ok?'public, max-age=30':'no-store');res.end(JSON.stringify(data))}catch(e){res.statusCode=502;res.end(JSON.stringify({ok:false,relay:'render-2',error:e.message}))}});server.listen(PORT,'0.0.0.0',()=>console.log(`DOAA relay listening on ${PORT}`));